# -*- coding: utf-8 -*-
import cv2
# Form implementation generated from reading ui file 'form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtWidgets
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QGraphicsScene


class Ui_MainWindow(object):
    def __init__(self):
        self.menu22 = None
        self.statusbar = None
        self.menu11 = None
        self.menubar = None
        self.pushButton = None
        self.pushButton_14 = None
        self.pushButton_13 = None
        self.verticalLayout_8 = None
        self.graphicsView_14 = None
        self.graphicsView_13 = None
        self.centralwidget = None
        self.MainWindow=None
        
    def setupUi(self, MainWindow):
        self.MainWindow = MainWindow
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.init_layout()
        self.graphicsView_13 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView_13.setMouseTracking(False)
        self.graphicsView_13.setObjectName("graphicsView_13")
        self.horizontalLayout_7.addWidget(self.graphicsView_13)
        self.graphicsView_14 = QtWidgets.QGraphicsView(self.horizontalLayoutWidget)
        self.graphicsView_14.setObjectName("graphicsView_14")
        self.horizontalLayout_7.addWidget(self.graphicsView_14)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(10)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.pushButton_13 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_13.setCheckable(False)
        self.pushButton_13.setChecked(False)
        self.pushButton_13.setObjectName("pushButton_13")
        self.verticalLayout_8.addWidget(self.pushButton_13)
        self.pushButton_14 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_14.setDefault(False)
        self.pushButton_14.setObjectName("pushButton_14")
        self.verticalLayout_8.addWidget(self.pushButton_14)
        self.horizontalLayout_7.addLayout(self.verticalLayout_8)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(40, 20, 93, 29))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        self.menu11 = QtWidgets.QMenu(self.menubar)
        self.menu11.setObjectName("menu11")
        self.menu22 = QtWidgets.QMenu(self.menubar)
        self.menu22.setObjectName("menu22")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menu11.menuAction())
        self.menubar.addAction(self.menu22.menuAction())

        self.retranslateUi(MainWindow)
        self.pushButton_13.clicked.connect(MainWindow.button_13_clicked)  # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        return self

    def init_layout(self):
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 120, 801, 381))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_7.setSizeConstraint(QtWidgets.QLayout.SetFixedSize)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButton_13.setText(_translate("MainWindow", "按钮"))
        self.pushButton_14.setText(_translate("MainWindow", "PushButton"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.menu11.setTitle(_translate("MainWindow", "11"))
        self.menu22.setTitle(_translate("MainWindow", "22"))
        self.scene = QGraphicsScene()
        self.scene2 = QGraphicsScene()

        self.graphicsView_13.setScene(self.scene)
        self.graphicsView_14.setScene(self.scene2)
        self.graphicsView_13
        self.graphicsView_13.show()
        self.graphicsView_14.show()
        self.open2show()

    def open2show(self):
        img = cv2.imread('../data/aa.jpg')
        cvimg = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)  # 把opencv 默认BGR转为通用的RGB
        y, x = img.shape[:-1]
        hbimg = cv2.cvtColor(cvimg, cv2.COLOR_RGB2GRAY)
        frame = QImage(cvimg, x, y, QImage.Format_RGB888)
        frame2 = QImage(hbimg, x, y, QImage.Format_Grayscale8)
        self.scene.clear()  # 先清空上次的残留
        self.scene2.clear()
        self.pix = QPixmap.fromImage(frame)
        self.pix2 = QPixmap.fromImage(frame2)
        self.scene.addPixmap(self.pix)
        self.scene2.addPixmap(self.pix2)
